### ISSUE TITLE
MAC 上是否能指定模型的安装位置？我的存储不够

### ISSUE THREAD

**Issue by freemank1224** [6174/comflowyspace#326]
如题？我想把里面涉及到的模型（Checkpoints等）放到外置硬盘，或者整个Comuflowy都安装在外置硬盘上，是否可以？有没有关键步骤的教程指导？谢谢，MAC的存储实在是太贵了……

**Comment by YanWenKun** [comment]
闲逛路过，不清楚 flowy 是咋操作的，ComfyUI 是可以配置的：

https://github.com/YanWenKun/ComfyUI-Windows-Portable/blob/main/README.zh.adoc#4-%E5%A4%96%E9%83%A8%E6%A8%A1%E5%9E%8B%E7%9B%AE%E5%BD%95

`extra_model_paths.yaml`

```
comfyui:
    base_path: D:\models\
    animatediff_models: animatediff_models
    animatediff_motion_lora: animatediff_motion_lora
    bert-base-uncased: bert-base-uncased
    checkpoints: checkpoints
    clip: clip
    clip_vision: clip_vision
    configs: configs
    controlnet: controlnet
    depthfm: depthfm
    diffusers: diffusers
    diffusion_models: |
        diffusion_models
        unet
    embeddings: embeddings
    facerestore_models: facerestore_models
    gligen: gligen
    grounding-dino: grounding-dino
    hypernetworks: hypernetworks
    insightface: insightface
    ipadapter: ipadapter
    loras: loras
    mmdets: mmdets
    onnx: onnx
    photomaker: photomaker
    reactor: reactor
    rembg: rembg
    sams: sams
    style_models: style_models
    text_encoders: text_encoders
    ultralytics: ultralytics
    unet: unet
    upscale_models: upscale_models
    vae: vae
    vae_approx: vae_approx
```
